version: "3.8"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN
      OWNER_ID: $OWNER_ID
      LOG_CHANNEL: $LOG_CHANNEL
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      DATABASE_URL: $DATABASE_URL
      BOT_USERNAME: $BOT_USERNAME
